### ISSUE TITLE
3D -  2D Correspondence

### ISSUE THREAD

**Issue by deysumitkr** [camera-localization/camera_localization#3]
- [ ] Initialize project
  - [ ] boiler plate stuffs - gitignore, readme, license, cmake, dirs, sample code..
  - [ ] app integration - CI, code review, linters ...
  - [ ] add opencv dependency - CI configs, cmake, sample code

- [ ] Correspondences
  - [ ] capture various views of pattern
  - [ ] feature detections and assign 3D coordinates
  - [ ] structures for correspondences and tracks of correspondences
